name: my_cats
description: A new Flutter project.
project_author: Yunus Karaaslan
project_author_email: karaaslan.21@hotmail.com
project_author_phone: +905319823347

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  provider: ^6.0.3
  flutter_native_splash: ^2.1.6
  flutter_staggered_grid_view: ^0.6.1
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
